const fs = require("fs");

const colleges = [
  { name: "Indian Institute of Technology Bombay", abbreviation: "IIT Bombay", state: "Maharashtra", type: "IIT" },
  { name: "Indian Institute of Technology Delhi", abbreviation: "IIT Delhi", state: "Delhi", type: "IIT" },
  { name: "Indian Institute of Technology Madras", abbreviation: "IIT Madras", state: "Tamil Nadu", type: "IIT" },
  { name: "Indian Institute of Technology Kanpur", abbreviation: "IIT Kanpur", state: "Uttar Pradesh", type: "IIT" },
  { name: "Indian Institute of Technology Kharagpur", abbreviation: "IIT KGP", state: "West Bengal", type: "IIT" },
  { name: "Indian Institute of Technology Roorkee", abbreviation: "IIT Roorkee", state: "Uttarakhand", type: "IIT" },
  { name: "Indian Institute of Technology Hyderabad", abbreviation: "IIT Hyderabad", state: "Telangana", type: "IIT" },
  { name: "Indian Institute of Technology Guwahati", abbreviation: "IIT Guwahati", state: "Assam", type: "IIT" },
  { name: "Indian Institute of Science", abbreviation: "IISc", state: "Karnataka", type: "Institute" },
  { name: "National Institute of Technology Trichy", abbreviation: "NIT Trichy", state: "Tamil Nadu", type: "NIT" },
  { name: "National Institute of Technology Warangal", abbreviation: "NIT Warangal", state: "Telangana", type: "NIT" },
  { name: "National Institute of Technology Surathkal", abbreviation: "NIT Surathkal", state: "Karnataka", type: "NIT" },
  { name: "National Institute of Technology Calicut", abbreviation: "NIT Calicut", state: "Kerala", type: "NIT" },
  { name: "Birla Institute of Technology and Science Pilani", abbreviation: "BITS Pilani", state: "Rajasthan", type: "Deemed" },
  { name: "Birla Institute of Technology and Science Goa", abbreviation: "BITS Goa", state: "Goa", type: "Deemed" },
  { name: "Birla Institute of Technology and Science Hyderabad", abbreviation: "BITS Hyderabad", state: "Telangana", type: "Deemed" },
  { name: "Vellore Institute of Technology", abbreviation: "VIT", state: "Tamil Nadu", type: "Deemed" },
  { name: "SRM Institute of Science and Technology", abbreviation: "SRM", state: "Tamil Nadu", type: "Deemed" },
  { name: "Manipal Academy of Higher Education", abbreviation: "Manipal", state: "Karnataka", type: "Deemed" },
  { name: "Amity University", abbreviation: "Amity", state: "Uttar Pradesh", type: "Private" },
  { name: "Symbiosis International University", abbreviation: "SIU", state: "Maharashtra", type: "Deemed" },
  { name: "Christ University", abbreviation: "Christ", state: "Karnataka", type: "Deemed" },
  { name: "Lovely Professional University", abbreviation: "LPU", state: "Punjab", type: "Private" },
  { name: "Chandigarh University", abbreviation: "CU", state: "Punjab", type: "Private" },
  { name: "Delhi University", abbreviation: "DU", state: "Delhi", type: "Central" },
  { name: "University of Mumbai", abbreviation: "Mumbai University", state: "Maharashtra", type: "State" },
  { name: "University of Calcutta", abbreviation: "CU", state: "West Bengal", type: "State" },
  { name: "University of Madras", abbreviation: "Madras University", state: "Tamil Nadu", type: "State" },
  { name: "Osmania University", abbreviation: "OU", state: "Telangana", type: "State" },
  { name: "Anna University", abbreviation: "Anna University", state: "Tamil Nadu", type: "State" },
  { name: "Pune University", abbreviation: "SPPU", state: "Maharashtra", type: "State" },
  { name: "Jawaharlal Nehru University", abbreviation: "JNU", state: "Delhi", type: "Central" },
  { name: "Hyderabad University", abbreviation: "UoH", state: "Telangana", type: "Central" },
  { name: "Jadavpur University", abbreviation: "JU", state: "West Bengal", type: "State" },
  { name: "Banaras Hindu University", abbreviation: "BHU", state: "Uttar Pradesh", type: "Central" },
  { name: "Aligarh Muslim University", abbreviation: "AMU", state: "Uttar Pradesh", type: "Central" },
  { name: "Indian Institute of Management Ahmedabad", abbreviation: "IIM Ahmedabad", state: "Gujarat", type: "IIM" },
  { name: "Indian Institute of Management Bangalore", abbreviation: "IIM Bangalore", state: "Karnataka", type: "IIM" },
  { name: "Indian Institute of Management Calcutta", abbreviation: "IIM Calcutta", state: "West Bengal", type: "IIM" },
  { name: "Indian Institute of Management Lucknow", abbreviation: "IIM Lucknow", state: "Uttar Pradesh", type: "IIM" },
  { name: "Veermata Jijabai Technological Institute", abbreviation: "VJTI", state: "Maharashtra", type: "Autonomous" },
  { name: "College of Engineering Pune", abbreviation: "COEP", state: "Maharashtra", type: "Autonomous" },
  { name: "PSG College of Technology", abbreviation: "PSG Tech", state: "Tamil Nadu", type: "Autonomous" },
  { name: "Coimbatore Institute of Technology", abbreviation: "CIT", state: "Tamil Nadu", type: "Autonomous" },
  { name: "RV College of Engineering", abbreviation: "RVCE", state: "Karnataka", type: "Autonomous" },
  { name: "PES University", abbreviation: "PES", state: "Karnataka", type: "Deemed" },
  { name: "MS Ramaiah Institute of Technology", abbreviation: "MSRIT", state: "Karnataka", type: "Autonomous" },
  { name: "BMS College of Engineering", abbreviation: "BMSCE", state: "Karnataka", type: "Autonomous" },
  { name: "Netaji Subhas University of Technology", abbreviation: "NSUT", state: "Delhi", type: "State" },
  { name: "Delhi Technological University", abbreviation: "DTU", state: "Delhi", type: "State" },
  { name: "Indraprastha Institute of Information Technology", abbreviation: "IIIT Delhi", state: "Delhi", type: "State" }
];

fs.writeFileSync("./data/india_colleges.json", JSON.stringify(colleges, null, 2));
console.log(`Built colleges database with ${colleges.length} entries`);
